[project]
name = "spark-skew"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jduran9987", email = "jduran9987@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.2",
    "pyarrow>=22.0.0",
    "boto3>=1.40.0",
]

[project.scripts]
spark-skew = "spark_skew:main"
generate-source-data = "generator.cli:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
